In [162]:
import plotly.graph_objects as go # or plotly.express as px
from plotly.subplots import make_subplots
import json
import pandas as pd
import numpy as np

In [163]:
with open('pokedex.json') as p:
    pokedex=json.load(p)

In [164]:
type(pokedex)

dict

In [165]:
pokedex.keys()

dict_keys(['pokemon'])

In [166]:
type(pokedex['pokemon'])

list

In [167]:
len(pokedex['pokemon'])

151

In [168]:
pokedex['pokemon'][0]

{'id': 1,
 'num': '001',
 'name': 'Bulbasaur',
 'img': 'http://www.serebii.net/pokemongo/pokemon/001.png',
 'type': ['Grass', 'Poison'],
 'height': '0.71 m',
 'weight': '6.9 kg',
 'candy': 'Bulbasaur Candy',
 'candy_count': 25,
 'egg': '2 km',
 'spawn_chance': 0.69,
 'avg_spawns': 69,
 'spawn_time': '20:00',
 'multipliers': [1.58],
 'weaknesses': ['Fire', 'Ice', 'Flying', 'Psychic'],
 'next_evolution': [{'num': '002', 'name': 'Ivysaur'},
  {'num': '003', 'name': 'Venusaur'}]}

In [169]:
pokedex['pokemon'][0].keys()

dict_keys(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy', 'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time', 'multipliers', 'weaknesses', 'next_evolution'])

In [170]:
pokedata= pd.DataFrame(pokedex['pokemon'])
pokedata.head(10)

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
5,6,006,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"[Fire, Flying]",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,None,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
6,7,007,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,[Water],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN
7,8,008,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,[Water],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
8,9,009,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,[Water],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,None,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '..."
9,10,010,Caterpie,http://www.serebii.net/pokemongo/pokemon/010.png,[Bug],0.30 m,2.9 kg,Caterpie Candy,12.0,2 km,3.0320,303.20,16:35,[1.05],"[Fire, Flying, Rock]","[{'num': '011', 'name': 'Metapod'}, {'num': '0...",NaN

In [171]:
pokedata[['type1', 'type2']] = pd.DataFrame(pokedata.type.tolist(), index=pokedata.index)
pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None

In [172]:
typegroup=pokedata.groupby('type1').count()['id']
typegroup

type1
Bug         12
Dragon       3
Electric     9
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      24
Poison      14
Psychic      8
Rock         9
Water       28
Name: id, dtype: int64

In [173]:
pokecolors_map = {
'Normal': '#A8A77A',
'Fire': '#EE8130',
'Water': '#6390F0',
'Electric': '#F7D02C',
'Grass': '#7AC74C',
'Ice': '#96D9D6',
'Fighting': '#C22E28',
'Poison': '#A33EA1',
'Ground': '#E2BF65',
'Flying': '#A98FF3',
'Psychic': '#F95587',
'Bug': '#A6B91A',
'Rock': '#B6A136',
'Ghost': '#735797',
'Dragon': '#6F35FC',
'Dark': '#705746',
'Steel': '#B7B7CE',
'Fairy': '#D685AD',
}

In [174]:
pokecolors=typegroup.index.map(pokecolors_map)
pokecolors=list(pokecolors)
pokecolors

['#A6B91A',
 '#6F35FC',
 '#F7D02C',
 '#C22E28',
 '#EE8130',
 '#735797',
 '#7AC74C',
 '#E2BF65',
 '#96D9D6',
 '#A8A77A',
 '#A33EA1',
 '#F95587',
 '#B6A136',
 '#6390F0']

In [175]:
fig1=go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values)])
fig1.show()

In [176]:
fig1=go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values, marker_color= pokecolors)])
fig1.show()

In [177]:
fig2 = go.Figure(data=[go.Pie(labels= typegroup.index, values=typegroup.values, marker= dict(colors=pokecolors), title= 'Gen 1 Pokemon by First Type')])
fig2.show()

In [178]:
pokedata.tail()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None

In [179]:
type(pokedata['next_evolution'][150])

float

In [180]:
conditions = [(pokedata["next_evolution"].apply(isinstance, args=(list,))) & (pokedata["prev_evolution"].apply(isinstance, args=(float,))),
              (pokedata["next_evolution"].apply(isinstance, args=(float,))) & (pokedata["prev_evolution"].apply(isinstance, args=(list,))),
              (pokedata["next_evolution"].apply(isinstance, args=(float,))) & (pokedata["prev_evolution"].apply(isinstance, args=(float,)))
              ]
choices = ["First", "Final", "Lone"]



pokedata['evolution_stage'] = np.select(conditions, choices, default="Middle")
pokedata.tail()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None,First
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None,Middle
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying,Final
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone

In [181]:
evolvegroup=pokedata.groupby('evolution_stage').count()['id']
evolvegroup

evolution_stage
Final     56
First     54
Lone      25
Middle    16
Name: id, dtype: int64

In [182]:
fig3= make_subplots(rows=1, cols=2, specs=[[{'type': 'domain'}, {'type': 'domain'}]])

fig3.add_trace(go.Pie(labels= typegroup.index, values=typegroup.values, marker= dict(colors=pokecolors), title= 'Gen 1 Pokemon by First Type'), 1,1)

fig3.add_trace(
    go.Pie(labels=evolvegroup.index, values=evolvegroup.values, title= 'Gen 1 Pokemon by Evolution Stage'), 1,2
)
fig3.show()

In [183]:
pokedata.head(1)

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.69,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,First

In [184]:
type(pokedata['weight'][0])

str

In [185]:
type(pokedata['height'][0])

str

In [186]:
pokedata['weight_kg'] = pokedata['weight'].str.replace(' kg', '', regex=False)
pokedata['weight_kg'] = pd.to_numeric(pokedata['weight_kg'])

In [187]:
pokedata['height_m'] = pokedata['height'].str.replace(' m', '', regex=False)
pokedata['height_m'] = pd.to_numeric(pokedata['height_m'])

pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,First,6.9,0.71
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,First,8.5,0.61
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09

In [188]:
traces = go.Scatter(
    x = pokedata['height_m'],
    y = pokedata['weight_kg'],
    mode = 'markers'
)

layout = go.Layout(title = {'text': 'Pokemon Weight and Height'},
                   xaxis = {'title': 'Weight in kg'},
                   yaxis = {'title': 'Height in m'})

fig4 = go.Figure(data = [traces], layout = layout)

fig4.show()

In [189]:
condition = pokedata['type1'].notna() & pokedata['type2'].notna()
pokedata['types'] = np.where(condition, pokedata['type1'] + ' & ' + pokedata['type2'], pokedata['type1'])
pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m,types
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,First,6.9,0.71,Grass & Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99,Grass & Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01,Grass & Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,First,8.5,0.61,Fire
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09,Fire

In [ ]:
trace1 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Lone']['name'],
    name = 'Lone'
)

trace2 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'First']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'First']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'First']['name'],
    name = 'First'
)

trace3 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Middle']['name'],
    name = 'Middle'
)

trace4 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Final']['name'],
    name = 'Final'
)

layout = go.Layout(title = {'text': 'Pokemon Weight and Height'},
                   xaxis = {'title': 'Weight in kg'},
                   yaxis = {'title': 'Height in m'})

fig4 = go.Figure(data = [trace1, trace2, trace3, trace4], layout = layout)

fig4.update_traces(mode = 'markers')

fig4.show()

In [208]:
trace1 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Lone']['name'],
    text= pokedata[pokedata['evolution_stage'] == 'Lone']['types'],
    name = 'Lone'
)

trace2 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'First']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'First']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'First']['name'],
    text= pokedata[pokedata['evolution_stage'] == 'First']['types'],
    name = 'First'
)

trace3 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Middle']['name'],
    text= pokedata[pokedata['evolution_stage'] == 'Middle']['type'],
    name = 'Middle'
)

trace4 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Final']['name'],
    text=pokedata[pokedata['evolution_stage'] == 'Final']['type'],
    name = 'Final'
)

layout = go.Layout(title = {'text': 'Pokemon Weight and Height'},
                   xaxis = {'title': 'Weight in kg'},
                   yaxis = {'title': 'Height in m'})

fig4 = go.Figure(data = [trace1, trace2, trace3, trace4], layout = layout)

fig4.update_traces(mode = 'markers', marker=dict(size=10, opacity=.5), hovertemplate="<b>%{customdata}</b>"\
                                                 '<br>%{text} Type'\
                                                    '<br>Weight: %{y}kg'\
                                                    '<br>Height: %{x}m'
                                                        )

fig4.update_layout(updatemenus = [dict(type='buttons', direction = 'left', x= 0.5, y= 1.15, showactive=True,
                                        buttons = list([dict(label='All', method = 'update', args = [{'visible':[True,True,True,True]}]),
                                                        dict(label='First', method = 'update', args = [{'visible':[False,True,False,False]}]),
                                                        dict(label='Middle', method = 'update', args = [{'visible':[False,False,True,False]}]),
                                                        dict(label='Final', method = 'update', args = [{'visible':[False,False,False,True]}]),
                                                        dict(label='Lone', method = 'update', args = [{'visible':[True,False,False,False]}])
                                                        ]))])


fig4.show()

In [211]:
trace1 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Lone']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Lone']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Lone']['name'],
    text= pokedata[pokedata['evolution_stage'] == 'Lone']['types'],
    marker_color="lightslategray",
    name = 'Lone'
)

trace2 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'First']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'First']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'First']['name'],
    text= pokedata[pokedata['evolution_stage'] == 'First']['types'],
    marker_color="plum",
    name = 'First'
)

trace3 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Middle']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Middle']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Middle']['name'],
    text= pokedata[pokedata['evolution_stage'] == 'Middle']['type'],
    marker_color="mediumvioletred",
    name = 'Middle'
)

trace4 = go.Scatter(
    x = pokedata[pokedata['evolution_stage'] == 'Final']['height_m'],
    y = pokedata[pokedata['evolution_stage'] == 'Final']['weight_kg'],
    customdata = pokedata[pokedata['evolution_stage'] == 'Final']['name'],
    text=pokedata[pokedata['evolution_stage'] == 'Final']['type'],
    marker_color="indigo",
    name = 'Final'
)

layout = go.Layout(title = {'text': 'Pokemon Weight and Height'},
                   xaxis = {'title': 'Weight in kg'},
                   yaxis = {'title': 'Height in m'},
                   showlegend=False)

fig4 = go.Figure(data = [trace1, trace2, trace3, trace4], layout = layout)

fig4.update_traces(mode = 'markers', marker=dict(size=10, opacity=.5), hovertemplate="<b>%{customdata}</b>"\
                                                 '<br>%{text} Type'\
                                                    '<br>Weight: %{y}kg'\
                                                    '<br>Height: %{x}m'
                                                        )

fig4.update_layout(updatemenus = [dict(direction = 'down', x= 0.5, xanchor= 'left', y= 1.15, yanchor= 'top', showactive=True,
                                        buttons = list([dict(label='All', method = 'update', args = [{'visible':[True,True,True,True]}]),
                                                        dict(label='First', method = 'update', args = [{'visible':[False,True,False,False]}]),
                                                        dict(label='Middle', method = 'update', args = [{'visible':[False,False,True,False]}]),
                                                        dict(label='Final', method = 'update', args = [{'visible':[False,False,False,True]}]),
                                                        dict(label='Lone', method = 'update', args = [{'visible':[True,False,False,False]}])
                                                        ]))])


fig4.show()