In [2]:
import pandas as pd

In [3]:
data_dict = {'a': [1,2,3], 'b':[4,5,6]}
data_list = [{'a': 1, 'b': 4}, {'a': 2, 'b': 5}, {'a': 3, 'b': 6}]

dat = pd.DataFrame(data_dict)
dat

   a  b
0  1  4
1  2  5
2  3  6

In [4]:
dat2 = pd.DataFrame(data_list)
dat2

   a  b
0  1  4
1  2  5
2  3  6

In [5]:
dat.head(1)

   a  b
0  1  4

In [6]:
dat.tail(1)

   a  b
2  3  6

In [7]:
dat['a']

0    1
1    2
2    3
Name: a, dtype: int64

In [8]:
dat.loc[0]

a    1
b    4
Name: 0, dtype: int64

In [9]:
dat.iloc[0]

a    1
b    4
Name: 0, dtype: int64

In [10]:
dat.index

RangeIndex(start=0, stop=3, step=1)

In [11]:
len(dat.index)

3

In [12]:
len(dat.columns)

2

In [13]:
dat[["a",'b']]

   a  b
0  1  4
1  2  5
2  3  6

In [14]:
dat[dat['a'] > 2]

   a  b
2  3  6

In [18]:
dat[dat['a'] > 2]['a']

2    3
Name: a, dtype: int64

In [19]:
dat.write_csv()

AttributeError: 'DataFrame' object has no attribute 'write_csv'

In [20]:
dat = pd.DataFrame(data_dict)
dat.to_csv("pandasChallange")

1. it lets us quickly see the changes we make
2. it lets people explore the data themselves and helps prevent an overload of information
3. i do like the idea of a community building something open source together, making plug ins to help streamline the workload and prossess. however, this can lead to a barrer of entry that can make it difficult for new people to join in. if you need to know about all the plugins and how to use them, its a lot more difficult than just downloading a corporate software that had instructions built in.